### ISSUE TITLE
Illumos image missing development files?

### ISSUE THREAD

**Issue by LecrisUT** [cross-rs/cross#1644]
I would like to try and recruit some help from cross project as well on investigating [this issue](https://github.com/aws/aws-lc-rs/pull/709#issuecomment-2685721357). From the error log:
```
   --- stderr
  Evaluating: AWS_LC_SYS_EXTERNAL_BINDGEN='0'
  Parsed: AWS_LC_SYS_EXTERNAL_BINDGEN=false
  Failure invoking external bindgen! 
  bindgen-PARAMS: --prefix-link-name aws_lc_0_26_0_ --allowlist-file .*(/|\\)openssl((/|\\)[^/\\]+)+\.h --allowlist-file .*(/|\\)rust_wrapper\.h --rustified-enum point_conversion_form_t --default-macro-constant-type signed --with-derive-default --with-derive-partialeq --with-derive-eq --raw-line 
  // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
  // SPDX-License-Identifier: Apache-2.0 OR ISC
   --generate functions,types,vars,methods,constructors,destructors /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/include/rust_wrapper.h --rust-target 1.59 --output /target/x86_64-unknown-illumos/release/build/aws-lc-sys-d08023f950b0ca18/out/bindings.rs --formatter rustfmt -- -I /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/include -I /home/runner/work/aws-lc-rs/aws-lc-rs/aws-lc-sys/aws-lc/include
  bindgen-STDOUT: 
  bindgen-STDERR: /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
  Unable to generate bindings: clang diagnosed error: /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
  thread 'main' panicked at aws-lc-sys/builder/main.rs:643:5:
  aws-lc-sys build failed. Please enable the 'bindgen' feature on aws-lc-rs or aws-lc-sys.For more information, see the aws-lc-rs User Guide: https://aws.github.io/aws-lc-rs/index.html
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
it seems that the C std library is missing some header files in the image. Is this something that should be fixed here or downstream?

**Comment by justsmth** [comment]
I believe this issue was resolved by [this PR](https://github.com/cross-rs/cross/pull/1651).

@LecrisUT - Would you confirm?

**Comment by LecrisUT** [comment]
Yes, I think it is. It is still an issue on `atuin` side since they are using the `cross` release, but if anything new comes up around this issue, I will reopen this.
